version: "3.8"

services:
  # web:
  #   build: ./web
  #   image: web
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - api
  #   networks:
  #     - frontend
  #   environment:
  #     - REACT_APP_ENDPOINT=http://api:8080

  api:
    build: ./api
    image: api
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - backend
      - frontend
    environment:
      - PORT=8080
      - MONGODB_URL=mongodb://mongodb:27017

  mongodb:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    volumes:
      - dbdata6:/data/db
    networks:
      - backend

volumes:
  dbdata6:

networks:
  backend:
  frontend:
