version: "3.8"

services:
  # web:
  #   build: ./web
  #   image: web
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - api
  #   environment:
  #     - api_endpoint=http://api:8080

  # api:
  #   build: ./api
  #   image: api
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - node-network

  mongodb:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network

volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge
