name: primary-server
version: 0.1.0.0

ghc-options: -Wall
  -Werror
  -Wincomplete-patterns
  -Wincomplete-record-updates
  -Wincomplete-uni-patterns
  -Wmissing-signatures
  -Wtabs
  -Wunused-imports
  -fno-warn-name-shadowing

default-extensions:
  - BangPatterns
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveGeneric
  - DerivingStrategies
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PatternSynonyms
  - PolyKinds
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators
  - ViewPatterns

dependencies:
  - base
  - protolude
  - aeson
  - text
  - lens
  - exceptions
  - servant
  - time
  - uuid
  - transformers
  - mtl
  - scientific
  - http-api-data
  - data-default
  - unordered-containers
  - qm-interpolated-string
  - errors

library:
  source-dirs: src/lib

executables:
  server:
    main: Main.hs
    source-dirs: src/app
    ghc-options:
      - -fPIC
      - -Werror
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - primary-server
      - mongoDB
      - servant-server
      - wai
      - wai-extra
      - warp
      - http-types
      - http-client
      - mtl
