resolver: lts-20.26

extra-deps:
  - morpheus-graphql-0.27.3
  - morpheus-graphql-core-0.27.3
  - morpheus-graphql-app-0.27.3
  - morpheus-graphql-code-gen-0.27.3
  - morpheus-graphql-code-gen-utils-0.27.3
  - morpheus-graphql-server-0.27.3
  - morpheus-graphql-client-0.27.3
  - morpheus-graphql-subscriptions-0.27.3

packages:
  - .
